### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by ijpatricio** [asteroid-dev/AsteroidApp#3]
Hello!

Thank you for this awesome work, looks super!

I'm getting a blank screen, just like in "normal chrome/firefox" when accessing my flash app.
I thought that just by install it now, got recent browser binaries.
with dumping `process.versions`, it seems chrome is on v78, so that should be good!

Any ideas what might be needed? Any steps I can make to help you debug this?

![image](https://user-images.githubusercontent.com/26031459/112964217-06072c80-9140-11eb-9fc1-752d3d8b77fe.png)

![image](https://user-images.githubusercontent.com/26031459/112964179-fdaef180-913f-11eb-9bf3-5350f54041c1.png)

**Comment by ijpatricio** [comment]
It turns out, it was because of self-signed certificate!

We may solve it, by adding the flag.

on `src/Main.js`, on line 8, as of current date, we have

```javascript
e.setAppUserModelId("nl.habbo.AsteroidApp");

e.commandLine.appendSwitch('ignore-certificate-errors', 'true'); // add this line
```

Would you accept a PR for this?

**Comment by asteroid-dev** [comment]
Done! Good work!

**Comment by ijpatricio** [comment]
My pleasure!
I'm still on first steps with Electron, and was a joy to tinker with it!

Do you think it is feasible to also bundle a php application? (Laravel)
Just one client, the desktop user, so, nothing fancy... just native php serving... sqlite for database... rendering html/js/css (vuejs app)
Do you see any way, how a start might be?
This bundle with `.dll` and `dmg`  contents feels so much rocket science for me, have no idea where to start 😺
